### ISSUE TITLE
catchall.pl timeout

### ISSUE THREAD

**Issue by w0rkplaceacct** [ZaphodB/powerdns-snippets#1]
The catchall.pl script is not working for me. Made the follwing additions to pdns.conf:

launch=pipe
pipe-command=/etc/pdns/catchall.pl
pipe-timeout=1000
pipebackend-abi-version=2 

And catchall.pl was made executable for the pdns user.

All queries time out.

**Comment by ZaphodB** [comment]
Hey,
sorry it has been quite a while, i made the error of watching all of powerdns/pdns and henceforth muting all notifications so i didn't see that you opened an issue.

While i was unable to confirm the queries timing out i can confirm that since PowerDNS seems to have moved on and now asks for SOA first, so it never gets to the point where it asks for an A record.

If you are still looking for an example pipe backend 
https://doc.powerdns.com/authoritative/backends/pipe.html
provides some inspiration.

I will look into adapting catchall.pl shortly.
